### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by wgaylord** [MinecraftForge/FernFlowerLegacy#5]
http://pastebin.com/yGqv2aSN

that is the output when runing gradle build

**Comment by matthewprenger** [comment]
Looks like a wrong import [here](https://github.com/MinecraftForge/FernFlower/blob/master/src/org/jetbrains/java/decompiler/main/rels/NestedClassProcessor.java#L46), should be using [this](https://github.com/MinecraftForge/FernFlower/blob/master/src/org/jetbrains/java/decompiler/code/CodeConstants.java). Oddly enough it still builds for me.

**Comment by chibill** [comment]
Maybe because I am on windows 10 and you might be on a OS that has the lib
in with java.

**Comment by cpw** [comment]
Heh, yeah, that import is wrong..

**Comment by wgaylord** [comment]
Actually remove the import codeconstants are imported already.

**Comment by wgaylord** [comment]
And replace the references.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/FernFlower/commit/3b04e422ba4902bbaf7b058fc96326dc5c7d9458
Fixed, old habbits of using ASM die hard :P
Also fixed unit tests and some errors they exposed while at it.

**Comment by wgaylord** [comment]
Thanks!
