### ISSUE TITLE
Unable to build on a jenkins server with out disabling tests.

### ISSUE THREAD

**Issue by wgaylord** [MinecraftForge/FernFlowerLegacy#7]
Because of the test in  MinecraftDecompilationTest needing the minecraft added manually it is hard to setup this to build on a Jenkins server. I know I could make it download the jar before compiling but it should not be that way.

**Comment by LexManos** [comment]
We know. And intentional. Once we get everything fixed up that we want to we'll clean things up and push to upstream until then its very much in a specifically targeting our use case setup.
